spring:
  data:
    mongodb:
      # 主机地址
      host: 127.0.0.1
      # 数据库
      database: blog
      # 默认端口是27017
      port: 27017
      #也可以使用uri连接
      #uri: mongodb://127.0.0.1:27017/comment
      field-naming-strategy : org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

logging:
  path: ./log
  level:
    org:
      springframework:
        kafka: ERROR
#        beans:
#          factory: DEBUG
#        context:
#          annotation: DEBUG
      apache:
       kafka: ERROR