spring:
  data:
    mongodb:
#      # 主机地址
#      host: 127.0.0.1
#      # 数据库
#      database: blog
#      # 默认端口是27017
#      port: 27017
      #uri连接 replica set
#      uri : mongodb://127.0.0.1:27017,127.0.0.1:27018,127.0.0.1:27019/blogdb?connect=replicaSet&slaveOk=true&replicaSet=myrs
      #uri连接 sharded cluster
      uri: mongodb://127.0.0.1:27017,127.0.0.1:27117/blogdb
      field-naming-strategy : org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

logging:
  path: ./log
  level:
    org:
      springframework:
        kafka: ERROR
#        beans:
#          factory: DEBUG
#        context:
#          annotation: DEBUG
      apache:
       kafka: ERROR